FROM registry.redhat.io/ubi10/python-312-minimal:10.0

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.8.22 /uv /uvx /bin/

# Copy the project into the image
ADD . /app
USER root
RUN chown -R 1001:0 /app
USER 1001

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /app
RUN uv sync --locked

CMD ["uv", "run", "main.py"]
