apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
  - admin
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-users
users:
  - user1
  - user2
  - user3
  - user4
  - user5

