apiVersion: v1
data:
  client-secret: YidCS1F0X1VibkVGRW81RHF4bm1RMWt3PT0n
kind: Secret
metadata:
  name: dashboard-oauth-client-secret
type: Opaque
---
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: dashboard-oauth-client
# This secret must match the one you created in step 1
secret: dashboard-oauth-client-secret
grantMethod: prompt
# --- THIS IS THE FIX ---
# We explicitly allow this client to request the user:full scope
scopes:
  - "user:full"
redirectURIs:
  # Add the URL you got from the 'oc get route' command
  # The path /oauth/callback is used by the oauth-proxy
  - "https://dashboard-route-dashboard-app.apps.cluster-5ghcn.dynamic.redhatworkshops.io/oauth/callback"
  